### ISSUE TITLE
unhandledRejection: "Error: Asset 842581764 does not exist" from SDK internally called getAssetInfo()

### ISSUE THREAD

**Issue by LogioTek** [reach-sh/humble-sdk#68]
Today I started getting these repeatable unhandledRejections involving ASA 842581764 ([https://algoexplorer.io/asset/842581764](https://algoexplorer.io/asset/842581764)) and I'm not doing anything with ASA in question. It occurs in 2 separate environments (dev and production) and originates in getAssetInfo().

\node_modules\@reach-sh\humble-sdk\node_modules\@reach-sh\stdlib\dist\cjs\ALGO.js:1428
                        throw Error("Asset ".concat(a, " does not exist"));
                              ^

Error: Asset 842581764 does not exist
    at failOk (\node_modules\@reach-sh\humble-sdk\node_modules\@reach-sh\stdlib\dist\cjs\ALGO.js:1428:31)
    at \node_modules\@reach-sh\humble-sdk\node_modules\@reach-sh\stdlib\dist\cjs\ALGO.js:611:30
    at step (\node_modules\@reach-sh\humble-sdk\node_modules\@reach-sh\stdlib\dist\cjs\ALGO.js:70:23)
    at Object.next (\node_modules\@reach-sh\humble-sdk\node_modules\@reach-sh\stdlib\dist\cjs\ALGO.js:51:53)
    at fulfilled (\node_modules\@reach-sh\humble-sdk\node_modules\@reach-sh\stdlib\dist\cjs\ALGO.js:42:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by LogioTek** [comment]
I guess it comes via subscribeToPoolStream().

**Comment by MrJackdaw** [comment]
> I guess it comes via subscribeToPoolStream().

Hey sorry about the late reply: I assume you found a workaround. For the record, you were correct: someone 
- created a pool, then 
- subsequently withdrew all the liquidity from it, and then
- deleted one of the tokens

The SDK ran into the error when trying to fetch the deleted token. We have updated it to exclude the pool when it sees this token ID. Apologies for the inconvenience.
